language: rust

branches:
  only:
    - master

rust:
  - 1.31.0
  - stable

os:
  - linux
  - osx
  - windows

matrix:
  fast_finish: true
  allow_failures:
    - os: windows

script:
  - cargo build
  - cargo test
  - cargo test --release
  - cargo build --features serde
  - cargo test --features serde
  - cargo test --features serde --release
  - cargo build --no-default-features
  - cargo test --no-default-features
  - cargo test --no-default-features --release
  - cargo build --no-default-features --features serde
  - cargo test --no-default-features --features serde
  - cargo test --no-default-features --features serde --release
