language: rust
cache: cargo

branches:
  only:
    - master

rust:
  - 1.32.0
  - stable

os:
  - linux
  - osx
  - windows

matrix:
  fast_finish: true
  allow_failures:
    # Travis CI's Windows tier is presently beta (slow / unreliable)
    - os: windows

install:
  - rustup component add rustfmt
  - rustup component add clippy-preview

script:
  - cargo fmt --all -- --check
  - cargo clippy --all
  - cargo build --release
  - cargo test --release
  - cargo doc --no-deps
