[package]
name = "rustsec"
description = "Client library for the RustSec security advisory database"
version = "0.0.0"
authors = ["Tony Arcieri <bascule@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rustsec/rustsec"
documentation = "https://github.com/rustsec/rustsec"
keywords = ["rustsec", "security", "advisory", "vulnerability"]

[dependencies]
