[package]
name        = "cvss"
description = "Common Vulnerability Scoring System parser/serializer"
version     = "0.3.0" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
repository  = "https://github.com/rustsec/cvss.rs/"
readme      = "README.md"
categories  = ["parser-implementations"]
keywords    = ["cvssv3", "security", "advisory", "vulnerability"]
edition     = "2018"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
serde = { version = "1", optional = true }

[features]
default = ["v3"]
v3 = []

[package.metadata.docs.rs]
all-features = true
