[package]
name          = "rustsec"
description   = "Client library for the RustSec security advisory database"
version       = "0.9.1" # Also update html_root_url in lib.rs when bumping this
authors       = ["Tony Arcieri <bascule@gmail.com>"]
license       = "MIT OR Apache-2.0"
homepage      = "https://github.com/rustsec/rustsec-crate/"
readme        = "README.md"
categories    = ["api-bindings", "development-tools"]
keywords      = ["rustsec", "security", "advisory", "vulnerability"]

[dependencies]
chrono = { version = "0.4", optional = true }
directories = "1.0.1"
failure = "0.1"
failure_derive = "0.1"
git2 = "0.7"
platforms = { version = "0.1", features = ["serde"] }
semver = { version = "0.9", features = ["serde"] }
serde = "1"
serde_derive = "1"
toml = "0.4"

[features]
default = ["chrono"]
